In [16]:
import pandas as pd
import numpy as np

In [29]:
## ERCOT 15-Minute Fuel Mix Generation (megawatt)(2020Q1-2024Q2)
FuelMix2024Q1= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_gen_all_15min_2024Q1.csv'
FuelMixlable2024Q1 = pd.read_csv(FuelMix2024Q1, skiprows=3)
FuelMix2024Q2= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_gen_all_15min_2024Q2.csv'
FuelMixlable2024Q2 = pd.read_csv(FuelMix2024Q2, skiprows=3)
FuelMix2024Q3= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_gen_all_15min_2024Q3.csv'
FuelMixlable2024Q3 = pd.read_csv(FuelMix2024Q3, skiprows=3)

FuelMix2023Q1= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_gen_all_15min_2023Q1.csv'
FuelMixlable2023Q1 = pd.read_csv(FuelMix2023Q1, skiprows=3)
FuelMix2023Q2= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_gen_all_15min_2023Q2.csv'
FuelMixlable2023Q2 = pd.read_csv(FuelMix2023Q2, skiprows=3)
FuelMix2023Q3= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_gen_all_15min_2023Q3.csv'
FuelMixlable2023Q3 = pd.read_csv(FuelMix2023Q3, skiprows=3)
FuelMix2023Q4= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_gen_all_15min_2023Q4.csv'
FuelMixlable2023Q4 = pd.read_csv(FuelMix2023Q4, skiprows=3)

FuelMix2022Q1= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_gen_all_15min_2022Q1.csv'
FuelMixlable2022Q1 = pd.read_csv(FuelMix2022Q1, skiprows=3)
FuelMix2022Q2= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_gen_all_15min_2022Q2.csv'
FuelMixlable2022Q2 = pd.read_csv(FuelMix2022Q2, skiprows=3)
FuelMix2022Q3= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_gen_all_15min_2022Q3.csv'
FuelMixlable2022Q3 = pd.read_csv(FuelMix2022Q3, skiprows=3)
FuelMix2022Q4= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_gen_all_15min_2022Q4.csv'
FuelMixlable2022Q4 = pd.read_csv(FuelMix2022Q4, skiprows=3)

FuelMix2021Q1= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_gen_all_15min_2021Q1.csv'
FuelMixlable2021Q1 = pd.read_csv(FuelMix2021Q1, skiprows=3)
FuelMix2021Q2= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_gen_all_15min_2021Q2.csv'
FuelMixlable2021Q2 = pd.read_csv(FuelMix2021Q2, skiprows=3)
FuelMix2021Q3= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_gen_all_15min_2021Q3.csv'
FuelMixlable2021Q3 = pd.read_csv(FuelMix2021Q3, skiprows=3)
FuelMix2021Q4= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_gen_all_15min_2021Q4.csv'
FuelMixlable2021Q4 = pd.read_csv(FuelMix2021Q4, skiprows=3)

FuelMix2020Q1= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_gen_all_15min_2020Q1.csv'
FuelMixlable2020Q1 = pd.read_csv(FuelMix2020Q1, skiprows=3)
FuelMix2020Q2= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_gen_all_15min_2020Q2.csv'
FuelMixlable2020Q2 = pd.read_csv(FuelMix2020Q2, skiprows=3)
FuelMix2020Q3= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_gen_all_15min_2020Q3.csv'
FuelMixlable2020Q3 = pd.read_csv(FuelMix2020Q3, skiprows=3)
FuelMix2020Q4= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_gen_all_15min_2020Q4.csv'
FuelMixlable2020Q4 = pd.read_csv(FuelMix2020Q4, skiprows=3)

print(FuelMixlable2020Q1.columns)
print(FuelMixlable2024Q3.columns)
print(FuelMixlable2020Q1.shape)
print(FuelMixlable2020Q2.shape)
print(FuelMixlable2020Q3.shape)
print(FuelMixlable2020Q4.shape)
print(FuelMixlable2021Q1.shape)
print(FuelMixlable2021Q2.shape)
print(FuelMixlable2021Q3.shape)
print(FuelMixlable2021Q4.shape)
print(FuelMixlable2022Q1.shape)
print(FuelMixlable2022Q2.shape)
print(FuelMixlable2022Q3.shape)
print(FuelMixlable2022Q4.shape)
print(FuelMixlable2023Q1.shape)
print(FuelMixlable2023Q2.shape)
print(FuelMixlable2023Q3.shape)
print(FuelMixlable2023Q4.shape)
print(FuelMixlable2024Q1.shape)
print(FuelMixlable2024Q2.shape)
print(FuelMixlable2024Q3.shape)

lables = [FuelMixlable2020Q1,FuelMixlable2020Q2,FuelMixlable2020Q3,FuelMixlable2020Q4,FuelMixlable2021Q1,FuelMixlable2021Q2,FuelMixlable2021Q3,FuelMixlable2021Q4,FuelMixlable2022Q1,FuelMixlable2022Q2,FuelMixlable2022Q3,FuelMixlable2022Q4,FuelMixlable2023Q1,FuelMixlable2023Q2,FuelMixlable2023Q3,FuelMixlable2023Q4,FuelMixlable2024Q1,FuelMixlable2024Q2,FuelMixlable2024Q3]
FuelMixdata = pd.DataFrame()
columns_to_extract = ['UTC Timestamp (Interval Ending)',
       'Local Timestamp Central Time (Interval Beginning)',
       'Local Timestamp Central Time (Interval Ending)', 'Local Date',
       'Hour Number', 'Total Generation (MW)', 'Biomass Generation (MW)',
       'Coal Generation (MW)', 'Gas Generation (MW)', 'Gas-CC Generation (MW)',
       'Hydro Generation (MW)', 'Nuclear Generation (MW)',
       'Other Generation (MW)', 'Solar Generation (MW)',
       'Wind Generation (MW)'
]
for lable in lables:
    selected_columns = lable[columns_to_extract]
    FuelMixdata = pd.concat([FuelMixdata, selected_columns], ignore_index=True)

FuelMixdata.sort_values(by='Local Timestamp Central Time (Interval Ending)', inplace=True)

FuelMixdata['Local Timestamp Central Time (Interval Ending)'] = pd.to_datetime(FuelMixdata['Local Timestamp Central Time (Interval Ending)'])

FuelMixdata['Local Timestamp Central Time (Interval Ending)'] = FuelMixdata['Local Timestamp Central Time (Interval Ending)'].dt.ceil('H')

FuelMix_Hourly_Data = FuelMixdata.groupby('Local Timestamp Central Time (Interval Ending)').agg({
    'UTC Timestamp (Interval Ending)': 'first',
    'Local Timestamp Central Time (Interval Beginning)': 'first',
    'Local Date': 'first',
    'Hour Number': 'first',
    'Total Generation (MW)': 'sum',
    'Biomass Generation (MW)': 'sum',
    'Coal Generation (MW)': 'sum',
    'Gas Generation (MW)': 'sum',
    'Gas-CC Generation (MW)': 'sum',
    'Hydro Generation (MW)': 'sum',
    'Nuclear Generation (MW)': 'sum',
    'Other Generation (MW)': 'sum',
    'Solar Generation (MW)': 'sum',
    'Wind Generation (MW)': 'sum'
}).reset_index()

FuelMix_Hourly_Data.head()

Index(['UTC Timestamp (Interval Ending)',
       'Local Timestamp Central Time (Interval Beginning)',
       'Local Timestamp Central Time (Interval Ending)', 'Local Date',
       'Hour Number', 'Total Generation (MW)', 'Biomass Generation (MW)',
       'Coal Generation (MW)', 'Gas Generation (MW)', 'Gas-CC Generation (MW)',
       'Hydro Generation (MW)', 'Nuclear Generation (MW)',
       'Other Generation (MW)', 'Solar Generation (MW)',
       'Wind Generation (MW)'],
      dtype='object')
Index(['UTC Timestamp (Interval Ending)',
       'Local Timestamp Central Time (Interval Beginning)',
       'Local Timestamp Central Time (Interval Ending)', 'Local Date',
       'Hour Number', 'Total Generation (MW)', 'Biomass Generation (MW)',
       'Coal Generation (MW)', 'Gas Generation (MW)', 'Gas-CC Generation (MW)',
       'Hydro Generation (MW)', 'Nuclear Generation (MW)',
       'Other Generation (MW)', 'Solar Generation (MW)', 'WSL Generation (MW)',
       'Wind Generation (MW)'],
      dtype='object')
(8732, 15)
(8736, 15)
(8832, 15)
(5856, 15)
(8636, 15)
(8736, 15)
(8832, 15)
(8836, 15)
(8636, 16)
(8736, 16)
(8832, 16)
(8836, 16)
(8636, 16)
(8736, 16)
(8832, 16)
(8832, 16)
(8732, 16)
(5856, 16)
(2976, 16)

,Local Timestamp Central Time (Interval Ending),UTC Timestamp (Interval Ending),Local Timestamp Central Time (Interval Beginning),Local Date,Hour Number,Total Generation (MW),Biomass Generation (MW),Coal Generation (MW),Gas Generation (MW),Gas-CC Generation (MW),Hydro Generation (MW),Nuclear Generation (MW),Other Generation (MW),Solar Generation (MW),Wind Generation (MW)
0,2020-01-01 01:00:00,2020-01-01 06:15:00,2020-01-01 00:00:00,2020-01-01,1,146810.946100,141.164040,23058.855628,2550.934672,49227.198196,110.431664,20394.741952,-3.809676,0.014,51331.415624
1,2020-01-01 02:00:00,2020-01-01 07:15:00,2020-01-01 01:00:00,2020-01-01,2,145641.089236,141.334816,22970.427228,2536.848140,46214.121768,75.028996,20390.138364,-1.728092,0.014,53314.904016
2,2020-01-01 03:00:00,2020-01-01 08:15:00,2020-01-01 02:00:00,2020-01-01,3,144077.945384,139.722048,22838.467844,2486.053348,42488.479880,42.694056,20393.346652,8.935440,0.014,55680.232116
3,2020-01-01 04:00:00,2020-01-01 09:15:00,2020-01-01 03:00:00,2020-01-01,4,142878.527116,140.065980,22364.793584,2461.974420,39704.510704,55.058968,20390.680492,-14.186168,0.028,57775.601136
4,2020-01-01 05:00:00,2020-01-01 10:15:00,2020-01-01 04:00:00,2020-01-01,5,143701.166284,139.633080,21958.002136,2465.651196,39683.963008,214.800108,20391.309460,-6.989084,0.014,58854.782380

In [20]:
## ERCOT 15-Minute Real-Time Locational Marginal Prices ($/megawatt) for Hubs 2020Q1-2024Q3)
LMP2024Q1= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_lmp_rt_15min_hubs_2024Q1.csv'
RTLMP2024Q1 = pd.read_csv(LMP2024Q1, skiprows=3)
LMP2024Q2= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_lmp_rt_15min_hubs_2024Q2.csv'
RTLMP2024Q2 = pd.read_csv(LMP2024Q2, skiprows=3)
LMP2024Q3= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_lmp_rt_15min_hubs_2024Q3.csv'
RTLMP2024Q3 = pd.read_csv(LMP2024Q3, skiprows=3)

LMP2023Q1= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_lmp_rt_15min_hubs_2023Q1.csv'
RTLMP2023Q1 = pd.read_csv(LMP2023Q1, skiprows=3)
LMP2023Q2= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_lmp_rt_15min_hubs_2023Q2.csv'
RTLMP2023Q2 = pd.read_csv(LMP2023Q2, skiprows=3)
LMP2023Q3= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_lmp_rt_15min_hubs_2023Q3.csv'
RTLMP2023Q3 = pd.read_csv(LMP2023Q3, skiprows=3)
LMP2023Q4= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_lmp_rt_15min_hubs_2023Q4.csv'
RTLMP2023Q4 = pd.read_csv(LMP2023Q4, skiprows=3)

LMP2022Q1= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_lmp_rt_15min_hubs_2022Q1.csv'
RTLMP2022Q1 = pd.read_csv(LMP2022Q1, skiprows=3)
LMP2022Q2= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_lmp_rt_15min_hubs_2022Q2.csv'
RTLMP2022Q2 = pd.read_csv(LMP2022Q2, skiprows=3)
LMP2022Q3= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_lmp_rt_15min_hubs_2022Q3.csv'
RTLMP2022Q3 = pd.read_csv(LMP2022Q3, skiprows=3)
LMP2022Q4= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_lmp_rt_15min_hubs_2022Q4.csv'
RTLMP2022Q4 = pd.read_csv(LMP2022Q4, skiprows=3)

LMP2021Q1= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_lmp_rt_15min_hubs_2021Q1.csv'
RTLMP2021Q1 = pd.read_csv(LMP2021Q1, skiprows=3)
LMP2021Q2= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_lmp_rt_15min_hubs_2021Q2.csv'
RTLMP2021Q2 = pd.read_csv(LMP2021Q2, skiprows=3)
LMP2021Q3= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_lmp_rt_15min_hubs_2021Q3.csv'
RTLMP2021Q3 = pd.read_csv(LMP2021Q3, skiprows=3)
LMP2021Q4= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_lmp_rt_15min_hubs_2021Q4.csv'
RTLMP2021Q4 = pd.read_csv(LMP2021Q4, skiprows=3)

LMP2020Q1= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_lmp_rt_15min_hubs_2020Q1.csv'
RTLMP2020Q1 = pd.read_csv(LMP2020Q1, skiprows=3)
LMP2020Q2= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_lmp_rt_15min_hubs_2020Q2.csv'
RTLMP2020Q2 = pd.read_csv(LMP2020Q2, skiprows=3)
LMP2020Q3= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_lmp_rt_15min_hubs_2020Q3.csv'
RTLMP2020Q3 = pd.read_csv(LMP2020Q3, skiprows=3)
LMP2020Q4= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_lmp_rt_15min_hubs_2020Q4.csv'
RTLMP2020Q4 = pd.read_csv(LMP2020Q4, skiprows=3)
 
print(RTLMP2020Q1.shape)
print(RTLMP2020Q2.shape)
print(RTLMP2020Q3.shape)
print(RTLMP2020Q4.shape)
print(RTLMP2021Q1.shape)
print(RTLMP2021Q2.shape)
print(RTLMP2021Q3.shape)
print(RTLMP2021Q4.shape)
print(RTLMP2022Q1.shape)
print(RTLMP2022Q2.shape)
print(RTLMP2022Q3.shape)
print(RTLMP2022Q4.shape)
print(RTLMP2023Q1.shape)
print(RTLMP2023Q2.shape)
print(RTLMP2023Q3.shape)
print(RTLMP2023Q4.shape)
print(RTLMP2024Q1.shape)
print(RTLMP2024Q2.shape)
print(RTLMP2024Q3.shape)

lables = [RTLMP2020Q1,RTLMP2020Q2,RTLMP2020Q3,RTLMP2020Q4,RTLMP2021Q1,RTLMP2021Q2,RTLMP2021Q3,RTLMP2021Q4,RTLMP2022Q1,RTLMP2022Q2,RTLMP2022Q3,RTLMP2022Q4,RTLMP2023Q1,RTLMP2023Q2,RTLMP2023Q3,RTLMP2023Q4,RTLMP2024Q1,RTLMP2024Q2,RTLMP2024Q3]
RTLMPdata = pd.DataFrame()
columns_to_extract = ['Local Timestamp Central Time (Interval Ending)','Bus average LMP', 'Houston LMP', 'Hub average LMP', 'North LMP', 'Panhandle LMP', 'South LMP', 'West LMP'
]
for lable in lables:
    selected_columns = lable[columns_to_extract]
    RTLMPdata = pd.concat([RTLMPdata, selected_columns], ignore_index=True)

RTLMPdata.sort_values(by='Local Timestamp Central Time (Interval Ending)', inplace=True)

RTLMPdata['Local Timestamp Central Time (Interval Ending)'] = pd.to_datetime(RTLMPdata['Local Timestamp Central Time (Interval Ending)'])

RTLMPdata['Local Timestamp Central Time (Interval Ending)'] = RTLMPdata['Local Timestamp Central Time (Interval Ending)'].dt.ceil('H')

RTLMP_Hourly_Data = RTLMPdata.groupby('Local Timestamp Central Time (Interval Ending)').agg({
    'Bus average LMP': 'mean',
    'Houston LMP': 'mean',
    'Hub average LMP': 'mean',
    'North LMP': 'mean',
    'Panhandle LMP': 'mean',
    'South LMP': 'mean',
    'West LMP': 'mean'
}).reset_index()

RTLMP_Hourly_Data.head()

(8732, 12)
(8736, 12)
(8832, 12)
(8829, 12)
(8608, 12)
(8727, 12)
(8829, 12)
(8819, 12)
(8614, 12)
(8732, 12)
(8641, 12)
(7242, 12)
(8636, 12)
(8736, 12)
(8832, 12)
(8836, 12)
(6440, 12)
(8714, 12)
(6494, 12)

,Local Timestamp Central Time (Interval Ending),Bus average LMP,Houston LMP,Hub average LMP,North LMP,Panhandle LMP,South LMP,West LMP
0,2020-01-01 01:00:00,13.7075,13.7075,13.7075,13.7075,-6.205,13.7075,13.7075
1,2020-01-01 02:00:00,13.2725,13.2725,13.2725,13.2725,-17.765,13.2725,13.2725
2,2020-01-01 03:00:00,11.3700,11.3700,11.3700,11.3700,-18.990,11.3700,11.3700
3,2020-01-01 04:00:00,9.4300,9.4325,9.4300,9.4300,-18.990,9.4375,9.4250
4,2020-01-01 05:00:00,8.6325,8.6325,8.6325,8.6325,-18.990,8.6325,8.6325

In [21]:
##ERCOT Hourly Actual Load (megawatt) by Weather Zone(2020-2024) 
lablefile2024= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_load_act_hr_2024.csv'
lable2024 = pd.read_csv(lablefile2024, skiprows=3)
lablefile2023= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_load_act_hr_2023.csv'
lable2023 = pd.read_csv(lablefile2023, skiprows=3)
lablefile2022= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_load_act_hr_2022.csv'
lable2022 = pd.read_csv(lablefile2022, skiprows=3)
lablefile2021= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_load_act_hr_2021.csv'
lable2021 = pd.read_csv(lablefile2021, skiprows=3)
lablefile2020= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_load_act_hr_2020.csv'
lable2020 = pd.read_csv(lablefile2020, skiprows=3)

lable2020.rename(columns={'TOT Actual Load (MW)': 'TOTAL Actual Load (MW)'}, inplace=True)
lable2020.rename(columns={'NCENT Actual Load (MW)': 'North Central Actual Load (MW)'}, inplace=True)
lable2020.rename(columns={'FWEST Actual Load (MW)': 'Far West Actual Load (MW)'}, inplace=True)
lable2020.rename(columns={'SCENT Actual Load (MW)': 'South Central Actual Load (MW)'}, inplace=True)
lable2020.rename(columns={'South Actual Load (MW)': 'Southern Actual Load (MW)'}, inplace=True)

print(lable2020.shape)
print(lable2021.shape)
print(lable2022.shape)
print(lable2023.shape)
print(lable2024.shape)

lables = [lable2020,lable2021,lable2022,lable2023,lable2024]
Act_Load_Data = pd.DataFrame()
columns_to_extract = ['Local Timestamp Central Time (Interval Ending)','TOTAL Actual Load (MW)', 'Coast Actual Load (MW)', 'East Actual Load (MW)', 'Far West Actual Load (MW)', 'North Actual Load (MW)', 'North Central Actual Load (MW)', 'Southern Actual Load (MW)', 'South Central Actual Load (MW)', 'West Actual Load (MW)']

for lable in lables:
    selected_columns = lable[columns_to_extract]
    Act_Load_Data = pd.concat([Act_Load_Data, selected_columns], ignore_index=True)

Act_Load_Data.sort_values(by= 'Local Timestamp Central Time (Interval Ending)', inplace=True)

Act_Load_Data.head()

(8784, 14)
(7654, 14)
(8746, 14)
(7600, 14)
(4901, 14)

,Local Timestamp Central Time (Interval Ending),TOTAL Actual Load (MW),Coast Actual Load (MW),East Actual Load (MW),Far West Actual Load (MW),North Actual Load (MW),North Central Actual Load (MW),Southern Actual Load (MW),South Central Actual Load (MW),West Actual Load (MW)
0,2020-01-01 01:00:00,36824.115099,9890.091522,1364.278198,3721.972022,773.878822,11719.863767,2707.841517,5473.246071,1172.943179
1,2020-01-01 02:00:00,36531.366488,9751.586415,1369.569694,3735.514034,775.063743,11639.455987,2706.844837,5387.380467,1165.951313
2,2020-01-01 03:00:00,36072.165020,9603.421087,1373.528720,3735.851866,774.153775,11515.421981,2650.378864,5270.331958,1149.076769
3,2020-01-01 04:00:00,35836.161867,9501.585599,1365.630426,3743.517881,778.097301,11518.359020,2586.709109,5200.960612,1141.301918
4,2020-01-01 05:00:00,35998.542722,9499.426925,1385.600323,3753.898979,784.077729,11649.293449,2548.852381,5230.298774,1147.094161

In [22]:
## .ERCOT Hourly Day-Ahead Locational Marginal Prices ($/megawatt) for Hubs(2020-2024)
lmpda2024= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_lmp_da_hr_hubs_2024.csv'
DALMP2024 = pd.read_csv(lmpda2024, skiprows=3)
lmpda2023= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_lmp_da_hr_hubs_2023.csv'
DALMP2023 = pd.read_csv(lmpda2023, skiprows=3)
lmpda2022= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_lmp_da_hr_hubs_2022.csv'
DALMP2022 = pd.read_csv(lmpda2022, skiprows=3)
lmpda2021= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_lmp_da_hr_hubs_2021.csv'
DALMP2021 = pd.read_csv(lmpda2021, skiprows=3)
lmpda2020= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_lmp_da_hr_hubs_2020.csv'
DALMP2020 = pd.read_csv(lmpda2020, skiprows=3)

print(DALMP2020.shape)
print(DALMP2021.shape)
print(DALMP2022.shape)
print(DALMP2023.shape)
print(DALMP2024.shape)

lables = [DALMP2020,DALMP2021,DALMP2022,DALMP2023,DALMP2024]
DA_LMP_Data = pd.DataFrame()
columns_to_extract = ['Local Timestamp Central Time (Interval Ending)','Bus average LMP', 'Houston LMP', 'Hub average LMP', 'North LMP', 'Panhandle LMP', 'South LMP', 'West LMP']

for lable in lables:
    selected_columns = lable[columns_to_extract]
    DA_LMP_Data = pd.concat([DA_LMP_Data, selected_columns], ignore_index=True)

DA_LMP_Data.sort_values(by= 'Local Timestamp Central Time (Interval Ending)', inplace=True)

DA_LMP_Data.head(10)

(8784, 12)
(8640, 12)
(8736, 12)
(7560, 12)
(4919, 12)

,Local Timestamp Central Time (Interval Ending),Bus average LMP,Houston LMP,Hub average LMP,North LMP,Panhandle LMP,South LMP,West LMP
0,2020-01-01 01:00:00,11.27,11.27,11.23,11.29,0.00,11.34,11.03
1,2020-01-01 02:00:00,10.04,9.73,9.99,10.01,-0.01,10.40,9.83
2,2020-01-01 03:00:00,9.58,9.58,9.52,9.64,-0.01,9.58,9.28
3,2020-01-01 04:00:00,9.95,9.65,9.89,9.95,-0.01,10.30,9.67
4,2020-01-01 05:00:00,10.22,10.18,10.13,10.30,-0.02,10.31,9.71
5,2020-01-01 06:00:00,10.79,10.69,10.73,10.81,-0.01,10.99,10.43
6,2020-01-01 07:00:00,13.42,13.05,13.35,13.42,0.00,13.80,13.13
7,2020-01-01 08:00:00,14.31,14.31,14.26,14.35,0.00,14.37,14.02
8,2020-01-01 09:00:00,14.43,14.23,14.35,14.38,0.77,15.02,13.78
9,2020-01-01 10:00:00,14.63,14.63,14.55,14.57,0.69,15.31,13.69

In [23]:
## ERCOT Hourly Forecast Load (megawatt) by Region(2021-2024)
forecastload2024= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_load_for_hr_2024.csv'
FCLoad2024 = pd.read_csv(forecastload2024, skiprows=3)
forecastload2023= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_load_for_hr_2023.csv'
FCLoad2023 = pd.read_csv(forecastload2023, skiprows=3)
forecastload2022= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_load_for_hr_2022.csv'
FCLoad2022 = pd.read_csv(forecastload2022, skiprows=3)
forecastload2021= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_load_for_hr_2021.csv'
FCLoad2021 = pd.read_csv(forecastload2021, skiprows=3)

print(FCLoad2021.shape)
print(FCLoad2022.shape)
print(FCLoad2023.shape)
print(FCLoad2024.shape)

lables = [FCLoad2021,FCLoad2022,FCLoad2023,FCLoad2024]
Forecast_Load_Data = pd.DataFrame()
columns_to_extract = ['Local Timestamp Central Time (Interval Ending)','SystemTotal Forecast Load (MW)', 'Houston Forecast Load (MW)', 'North Forecast Load (MW)', 'South Forecast Load (MW)', 'West Forecast Load (MW)']

for lable in lables:
    selected_columns = lable[columns_to_extract]
    Forecast_Load_Data = pd.concat([Forecast_Load_Data, selected_columns], ignore_index=True)

Forecast_Load_Data.sort_values(by= 'Local Timestamp Central Time (Interval Ending)', inplace=True)

Forecast_Load_Data.head(10)

(7056, 10)
(6791, 10)
(7032, 10)
(4919, 10)

,Local Timestamp Central Time (Interval Ending),SystemTotal Forecast Load (MW),Houston Forecast Load (MW),North Forecast Load (MW),South Forecast Load (MW),West Forecast Load (MW)
0,2021-03-03 01:00:00,36783.0,9575.3633,13002.2036,8948.5964,5256.8367
1,2021-03-03 02:00:00,36567.0,9496.1347,13014.3622,8784.1859,5272.3172
2,2021-03-03 03:00:00,36354.0,9585.0147,12660.8633,8803.9249,5304.1971
3,2021-03-03 04:00:00,37020.0,9601.4498,13159.1021,8911.2320,5348.2161
4,2021-03-03 05:00:00,38344.0,9913.2523,13709.0685,9334.2961,5387.3831
5,2021-03-03 06:00:00,41331.0,10584.1368,15151.8568,10116.8519,5478.1545
6,2021-03-03 07:00:00,45697.0,11461.7607,17030.1387,11506.3785,5698.7221
7,2021-03-03 08:00:00,47222.0,11679.8749,17913.2099,11839.9194,5788.9958
8,2021-03-03 09:00:00,45324.0,11706.4037,16756.5856,11228.4924,5632.5183
9,2021-03-03 10:00:00,43344.0,11354.9401,15927.4366,10633.0822,5428.5411

In [42]:
## ERCOT Hourly Imports and Exports (megawatt) by DC Tie Line(2021-2024)

## Index delete 'Comision Federal de Electricidad, Eagle Pass Net Export (MW)'

DC2024= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_int_all_hr_2024.csv'
Ex_Im_Load_2024 = pd.read_csv(DC2024, skiprows=3)
DC2023= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_int_all_hr_2023.csv'
Ex_Im_Load_2023 = pd.read_csv(DC2023, skiprows=3)
DC2022= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_int_all_hr_2022.csv'
Ex_Im_Load_2022 = pd.read_csv(DC2022, skiprows=3)
DC2021= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_int_all_hr_2021.csv'
Ex_Im_Load_2021 = pd.read_csv(DC2021, skiprows=3)

print(Ex_Im_Load_2021.shape)
print(Ex_Im_Load_2022.shape)
print(Ex_Im_Load_2023.shape)
print(Ex_Im_Load_2024.shape)

print(Ex_Im_Load_2021.columns)
print(Ex_Im_Load_2022.columns)
print(Ex_Im_Load_2023.columns)
print(Ex_Im_Load_2024.columns)

lables = [Ex_Im_Load_2021,Ex_Im_Load_2022,Ex_Im_Load_2023,Ex_Im_Load_2024]
Ex_Im_Data = pd.DataFrame()
columns_to_extract = [
       'Local Timestamp Central Time (Interval Ending)',
       'Comision Federal de Electricidad, Laredo Net Export (MW)',
       'Comision Federal de Electricidad, Railroad Net Export (MW)',
       'Southwest Power Pool, East Net Export (MW)',
       'Southwest Power Pool, North Net Export (MW)']

for lable in lables:
    selected_columns = lable[columns_to_extract]
    Ex_Im_Data = pd.concat([Ex_Im_Data, selected_columns], ignore_index=True)

Ex_Im_Data.sort_values(by= 'Local Timestamp Central Time (Interval Ending)', inplace=True)

Ex_Im_Data['Local Timestamp Central Time (Interval Ending)'] = pd.to_datetime(Ex_Im_Data['Local Timestamp Central Time (Interval Ending)'])

Ex_Im_Data['Local Timestamp Central Time (Interval Ending)'] = Ex_Im_Data['Local Timestamp Central Time (Interval Ending)'].dt.ceil('H')

Ex_Im_Data.head(10)

(6621, 10)
(8194, 10)
(7673, 10)
(4849, 9)
Index(['UTC Timestamp (Interval Ending)',
       'Local Timestamp Central Time (Interval Beginning)',
       'Local Timestamp Central Time (Interval Ending)', 'Local Date',
       'Hour Number',
       'Comision Federal de Electricidad, Eagle Pass Net Export (MW)',
       'Comision Federal de Electricidad, Laredo Net Export (MW)',
       'Comision Federal de Electricidad, Railroad Net Export (MW)',
       'Southwest Power Pool, East Net Export (MW)',
       'Southwest Power Pool, North Net Export (MW)'],
      dtype='object')
Index(['UTC Timestamp (Interval Ending)',
       'Local Timestamp Central Time (Interval Beginning)',
       'Local Timestamp Central Time (Interval Ending)', 'Local Date',
       'Hour Number',
       'Comision Federal de Electricidad, Eagle Pass Net Export (MW)',
       'Comision Federal de Electricidad, Laredo Net Export (MW)',
       'Comision Federal de Electricidad, Railroad Net Export (MW)',
       'Southwest Power Pool, East Net Export (MW)',
       'Southwest Power Pool, North Net Export (MW)'],
      dtype='object')
Index(['UTC Timestamp (Interval Ending)',
       'Local Timestamp Central Time (Interval Beginning)',
       'Local Timestamp Central Time (Interval Ending)', 'Local Date',
       'Hour Number',
       'Comision Federal de Electricidad, Eagle Pass Net Export (MW)',
       'Comision Federal de Electricidad, Laredo Net Export (MW)',
       'Comision Federal de Electricidad, Railroad Net Export (MW)',
       'Southwest Power Pool, East Net Export (MW)',
       'Southwest Power Pool, North Net Export (MW)'],
      dtype='object')
Index(['UTC Timestamp (Interval Ending)',
       'Local Timestamp Central Time (Interval Beginning)',
       'Local Timestamp Central Time (Interval Ending)', 'Local Date',
       'Hour Number',
       'Comision Federal de Electricidad, Laredo Net Export (MW)',
       'Comision Federal de Electricidad, Railroad Net Export (MW)',
       'Southwest Power Pool, East Net Export (MW)',
       'Southwest Power Pool, North Net Export (MW)'],
      dtype='object')

,Local Timestamp Central Time (Interval Ending),"Comision Federal de Electricidad, Laredo Net Export (MW)","Comision Federal de Electricidad, Railroad Net Export (MW)","Southwest Power Pool, East Net Export (MW)","Southwest Power Pool, North Net Export (MW)"
0,2021-03-30 13:00:00,-0.4,0.0,1.000489,-218.599991
1,2021-03-30 14:00:00,-0.4,0.0,1.000489,-218.399994
2,2021-03-30 15:00:00,-0.4,0.0,1.000489,-198.699997
3,2021-03-30 16:00:00,-0.3,-14.1,0.000000,-218.500000
4,2021-03-30 17:00:00,-0.3,-14.1,0.000000,-218.500000
5,2021-03-30 18:00:00,-0.2,-14.0,0.000000,-218.699997
6,2021-03-30 19:00:00,-0.4,0.0,0.000000,-218.599991
7,2021-03-30 20:00:00,-0.4,0.0,0.000000,-218.599991
8,2021-03-30 21:00:00,-0.7,0.0,1.000489,-218.300003
9,2021-03-30 22:00:00,-0.3,0.0,0.000000,-218.399994

In [26]:
## ERCOT Hourly Temperatures (Fahrenheit) in Major Cities(2020-2024)
tempfile2024= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_temp_hr_2024.csv'
temp2024 = pd.read_csv(tempfile2024, skiprows=3)
tempfile2023= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_temp_hr_2023.csv'
temp2023 = pd.read_csv(tempfile2023, skiprows=3)
tempfile2022= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_temp_hr_2022.csv'
temp2022 = pd.read_csv(tempfile2022, skiprows=3)
tempfile2021= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_temp_hr_2021.csv'
temp2021 = pd.read_csv(tempfile2021, skiprows=3)
tempfile2020= r'/Users/caoguangjing/Desktop/catalan.ai/data/ercot_temp_hr_2020.csv'
temp2020 = pd.read_csv(tempfile2020, skiprows=3)

print(temp2020.shape)
print(temp2021.shape)
print(temp2022.shape)
print(temp2023.shape)
print(temp2024.shape)

temps = [temp2020,temp2021,temp2022,temp2023,temp2024]

all_years_temp = pd.DataFrame()

for i, temp in enumerate(temps):
    temps[i]['Average Temperature (Fahrenheit)'] = (temps[i]['Dallas / Fort Worth Temperature (Fahrenheit)'] + 
                                                    temps[i]['Houston International Airport Temperature (Fahrenheit)']) / 2
    
    temp_selected_columns = [
        'Local Timestamp Central Time (Interval Ending)',
        'Average Temperature (Fahrenheit)',
        'Dallas / Fort Worth Temperature (Fahrenheit)',
        'Dallas / Fort Worth Temperature Observation Time (Central)',
        'Houston International Airport Temperature (Fahrenheit)',
        'Houston International Airport Temperature Observation Time (Central)'
    ]
    
    selected_columns = temps[i][temp_selected_columns]
    all_years_temp = pd.concat([all_years_temp, selected_columns], ignore_index=True)

# 排序
all_years_temp.sort_values(by='Local Timestamp Central Time (Interval Ending)', inplace=True)

# 显示结果
all_years_temp.head()

(8782, 9)
(8758, 9)
(8674, 9)
(8754, 9)
(5415, 9)

,Local Timestamp Central Time (Interval Ending),Average Temperature (Fahrenheit),Dallas / Fort Worth Temperature (Fahrenheit),Dallas / Fort Worth Temperature Observation Time (Central),Houston International Airport Temperature (Fahrenheit),Houston International Airport Temperature Observation Time (Central)
0,2020-01-01 01:00:00,45.05,42.1,2020-01-01 00:53:00,48.0,2020-01-01 00:53:00
1,2020-01-01 02:00:00,45.05,42.1,2020-01-01 01:53:00,48.0,2020-01-01 01:53:00
2,2020-01-01 03:00:00,45.95,43.0,2020-01-01 02:53:00,48.9,2020-01-01 02:53:00
3,2020-01-01 04:00:00,46.05,42.1,2020-01-01 03:53:00,50.0,2020-01-01 03:53:00
4,2020-01-01 05:00:00,46.05,42.1,2020-01-01 04:53:00,50.0,2020-01-01 04:53:00

In [43]:
# create a whole dataframe
dataframes = [FuelMix_Hourly_Data,RTLMP_Hourly_Data,Act_Load_Data,DA_LMP_Data,Forecast_Load_Data,Ex_Im_Data,all_years_temp] 

for df in dataframes:
    df['Local Timestamp Central Time (Interval Ending)'] = pd.to_datetime(df['Local Timestamp Central Time (Interval Ending)'])

merged_df = dataframes[0]

for df in dataframes[1:]:
    merged_df = pd.merge(
        merged_df, 
        df, 
        on='Local Timestamp Central Time (Interval Ending)', 
        how='inner')

merged_df.head(10)

,Local Timestamp Central Time (Interval Ending),UTC Timestamp (Interval Ending),Local Timestamp Central Time (Interval Beginning),Local Date,Hour Number,Total Generation (MW),Biomass Generation (MW),Coal Generation (MW),Gas Generation (MW),Gas-CC Generation (MW),...,West Forecast Load (MW),"Comision Federal de Electricidad, Laredo Net Export (MW)","Comision Federal de Electricidad, Railroad Net Export (MW)","Southwest Power Pool, East Net Export (MW)","Southwest Power Pool, North Net Export (MW)",Average Temperature (Fahrenheit),Dallas / Fort Worth Temperature (Fahrenheit),Dallas / Fort Worth Temperature Observation Time (Central),Houston International Airport Temperature (Fahrenheit),Houston International Airport Temperature Observation Time (Central)
0,2021-03-30 13:00:00,2021-03-30 17:15:00,2021-03-30 12:00:00,2021-03-30,13,162449.760572,99.305516,30638.785592,9368.176724,42215.318872,...,5060.598820,-0.4,0.0,1.000489,-218.599991,77.45,75.9,2021-03-30 12:53:00,79.0,2021-03-30 12:53:00
1,2021-03-30 14:00:00,2021-03-30 18:15:00,2021-03-30 13:00:00,2021-03-30,14,165833.018628,105.794500,31253.448100,9125.563332,47434.423340,...,5104.484835,-0.4,0.0,1.000489,-218.399994,78.50,75.0,2021-03-30 13:53:00,82.0,2021-03-30 13:53:00
2,2021-03-30 15:00:00,2021-03-30 19:15:00,2021-03-30 14:00:00,2021-03-30,15,168894.353208,107.544116,33190.147680,9889.303080,50777.592356,...,5159.510683,-0.4,0.0,1.000489,-198.699997,78.00,75.9,2021-03-30 14:53:00,80.1,2021-03-30 14:53:00
3,2021-03-30 16:00:00,2021-03-30 20:15:00,2021-03-30 15:00:00,2021-03-30,16,171731.267112,108.993848,34135.815652,12646.939040,53179.842612,...,5232.458800,-0.3,-14.1,0.000000,-218.500000,79.50,77.0,2021-03-30 15:53:00,82.0,2021-03-30 15:53:00
4,2021-03-30 17:00:00,2021-03-30 21:15:00,2021-03-30 16:00:00,2021-03-30,17,174894.914444,109.167588,34200.205204,17101.383700,53928.048544,...,5288.337110,-0.3,-14.1,0.000000,-218.500000,79.40,75.9,2021-03-30 16:53:00,82.9,2021-03-30 16:53:00
5,2021-03-30 18:00:00,2021-03-30 22:15:00,2021-03-30 17:00:00,2021-03-30,18,176219.154476,109.130212,34120.840828,16747.149452,53836.017940,...,5322.601979,-0.2,-14.0,0.000000,-218.699997,80.05,78.1,2021-03-30 17:53:00,82.0,2021-03-30 17:53:00
6,2021-03-30 19:00:00,2021-03-30 23:15:00,2021-03-30 18:00:00,2021-03-30,19,175092.713256,109.676308,33913.718220,12620.277004,54162.154600,...,5325.073036,-0.4,0.0,0.000000,-218.599991,79.10,78.1,2021-03-30 18:53:00,80.1,2021-03-30 18:53:00
7,2021-03-30 20:00:00,2021-03-31 00:15:00,2021-03-30 19:00:00,2021-03-30,20,174903.018692,109.792204,33804.397748,10422.931016,53755.251316,...,5303.650911,-0.4,0.0,0.000000,-218.599991,76.55,75.0,2021-03-30 19:53:00,78.1,2021-03-30 19:53:00
8,2021-03-30 21:00:00,2021-03-31 01:15:00,2021-03-30 20:00:00,2021-03-30,21,177710.536584,110.088368,33235.518280,7112.802380,51418.657672,...,5312.219255,-0.7,0.0,1.000489,-218.300003,75.00,73.0,2021-03-30 20:53:00,77.0,2021-03-30 20:53:00
9,2021-03-30 22:00:00,2021-03-31 02:15:00,2021-03-30 21:00:00,2021-03-30,22,172895.061456,110.303588,28618.779692,4887.006536,45039.332228,...,5258.982820,-0.3,0.0,0.000000,-218.399994,75.00,75.0,2021-03-30 21:53:00,75.0,2021-03-30 21:53:00

In [44]:
merged_df.shape

(23936, 52)